{{- if not .Values.disable.x10000FileService }}

---
### AlletraMP X10000 NFS CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: alletrastoragemp-x10000-nfs-csp-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: alletrastoragemp-x10000-nfs-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: alletrastoragemp-x10000-nfs-csp


---
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alletrastoragemp-x10000-nfs-csp
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: alletrastoragemp-x10000-nfs-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: alletrastoragemp-x10000-nfs-csp
        {{- if .Values.csp.labels }}
{{ toYaml .Values.csp.labels | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: hpe-csp-sa
      hostNetwork: true
      priorityClassName: system-cluster-critical
      containers:
        - name: alletrastoragemp-x10000-nfs-csp
          image: {{ .Values.images.x10000FileServiceCSP | quote }}
          resources:
            {{- toYaml .Values.csp.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
{{- end }}
